apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-frontend
  namespace: zabbix
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: zabbix-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
